on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 1 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        id: checkVersion
        continue-on-error: true
        run: |
          FRP_VERSION=$(curl -fsSI https://github.com/fatedier/frp/releases/latest | grep location | tr -d '\r' | sed 's/.*\/v//')
          if curl -fs https://hub.docker.com/v2/repositories/gera2ld/frp/tags/$FRP_VERSION > /dev/null; then
            echo Version exists: $FRP_VERSION
            exit 1
          else
            echo New version found: $FRP_VERSION
          fi
          echo FRP_VERSION=$FRP_VERSION >> $GITHUB_ENV
      - name: Set up Docker Buildx
        if: steps.checkVersion.outcome == 'success'
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: steps.checkVersion.outcome == 'success'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps.checkVersion.outcome == 'success'
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: gera2ld/frp:latest,gera2ld/frp:${{ env.FRP_VERSION }}
